"""add password reset fields to users

Revision ID: 3842778e4ed8
Revises: 580148e2242d
Create Date: 2026-01-13 17:25:34.538527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3842778e4ed8'
down_revision: Union[str, Sequence[str], None] = '580148e2242d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('password_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_reset_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['password_reset_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'password_reset_by')
    op.drop_column('users', 'password_reset_at')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
