"""implement_accounting_system

Revision ID: 580148e2242d
Revises: 5c522b5a0003
Create Date: 2026-01-13 09:34:47.875517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '580148e2242d'
down_revision: Union[str, Sequence[str], None] = '5c522b5a0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types first
    housestatus_enum = sa.Enum('ACTIVE', 'BANK_OWNED', 'VACANT', 'ARCHIVED', 'SUSPENDED', name='housestatus')
    housestatus_enum.create(op.get_bind())
    
    invoicestatus_enum = sa.Enum('ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoicestatus')
    invoicestatus_enum.create(op.get_bind())
    
    payinstatus_enum = sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='payinstatus')
    payinstatus_enum.create(op.get_bind())
    op.create_table('credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_id'), 'credit_notes', ['id'], unique=False)
    op.create_table('income_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('payin_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payin_id'], ['payin_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payin_id')
    )
    op.create_index(op.f('ix_income_transactions_id'), 'income_transactions', ['id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('income_transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['income_transaction_id'], ['income_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payments_id'), 'invoice_payments', ['id'], unique=False)
    op.drop_index('ix_invoice_items_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    
    # Add nullable columns first
    op.add_column('houses', sa.Column('house_code', sa.String(length=20), nullable=True))
    op.add_column('houses', sa.Column('house_status', housestatus_enum, nullable=True))
    op.add_column('houses', sa.Column('owner_name', sa.String(length=255), nullable=True))
    
    # Update existing data
    op.execute("UPDATE houses SET house_code = house_no WHERE house_code IS NULL")
    op.execute("UPDATE houses SET house_status = 'ACTIVE' WHERE house_status IS NULL AND status = 'active'")
    op.execute("UPDATE houses SET house_status = 'ARCHIVED' WHERE house_status IS NULL AND status = 'inactive'")
    op.execute("UPDATE houses SET house_status = 'ACTIVE' WHERE house_status IS NULL")  # Default fallback
    op.execute("UPDATE houses SET owner_name = 'Owner of ' || house_no WHERE owner_name IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('houses', 'house_code', nullable=False)
    op.execute("ALTER TABLE houses ALTER COLUMN house_status TYPE housestatus USING house_status::housestatus")
    op.alter_column('houses', 'house_status', nullable=False) 
    op.alter_column('houses', 'owner_name', nullable=False)
    op.drop_constraint('houses_house_no_key', 'houses', type_='unique')
    op.drop_index('ix_houses_house_no', table_name='houses')
    op.create_index(op.f('ix_houses_house_code'), 'houses', ['house_code'], unique=True)
    op.drop_column('houses', 'house_no')
    op.drop_column('houses', 'status')
    op.add_column('invoices', sa.Column('cycle_year', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('cycle_month', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('issue_date', sa.Date(), nullable=False))
    op.add_column('invoices', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('invoices', 'due_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)
    
    # Update existing invoice status values before changing type
    op.execute("UPDATE invoices SET status = 'ISSUED' WHERE status = 'draft'")
    op.execute("UPDATE invoices SET status = 'ISSUED' WHERE status = 'sent'") 
    op.execute("UPDATE invoices SET status = 'PAID' WHERE status = 'paid'")
    op.execute("UPDATE invoices SET status = 'CANCELLED' WHERE status = 'cancelled'")
    op.execute("UPDATE invoices SET status = 'ISSUED' WHERE status = 'overdue'")
    op.execute("UPDATE invoices SET status = 'ISSUED' WHERE status NOT IN ('ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')")
    
    # Use raw SQL to change the type with USING clause
    op.execute("ALTER TABLE invoices ALTER COLUMN status TYPE invoicestatus USING status::invoicestatus")
    op.drop_constraint('invoices_invoice_no_key', 'invoices', type_='unique')
    op.drop_index('ix_invoices_invoice_no', table_name='invoices')
    op.create_unique_constraint('unique_house_cycle', 'invoices', ['house_id', 'cycle_year', 'cycle_month'])
    op.create_foreign_key(None, 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_column('invoices', 'invoice_no')
    op.drop_column('invoices', 'period_start')
    op.drop_column('invoices', 'period_end')
    op.add_column('payin_reports', sa.Column('accepted_by', sa.Integer(), nullable=True))
    op.add_column('payin_reports', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing payin status values before changing type
    op.execute("UPDATE payin_reports SET status = 'PENDING' WHERE status = 'pending'")
    op.execute("UPDATE payin_reports SET status = 'ACCEPTED' WHERE status = 'approved'")
    op.execute("UPDATE payin_reports SET status = 'REJECTED' WHERE status = 'rejected'")
    op.execute("UPDATE payin_reports SET status = 'PENDING' WHERE status NOT IN ('PENDING', 'ACCEPTED', 'REJECTED')")
    
    # Use raw SQL to change the type with USING clause  
    op.execute("ALTER TABLE payin_reports ALTER COLUMN status TYPE payinstatus USING status::payinstatus")
    op.create_foreign_key(None, 'payin_reports', 'users', ['accepted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payin_reports', type_='foreignkey')
    op.alter_column('payin_reports', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='payinstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('payin_reports', 'accepted_at')
    op.drop_column('payin_reports', 'accepted_by')
    op.add_column('invoices', sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('invoice_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint('unique_house_cycle', 'invoices', type_='unique')
    op.create_index('ix_invoices_invoice_no', 'invoices', ['invoice_no'], unique=True)
    op.create_unique_constraint('invoices_invoice_no_key', 'invoices', ['invoice_no'])
    op.alter_column('invoices', 'status',
               existing_type=sa.Enum('ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='invoicestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('invoices', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('invoices', 'created_by')
    op.drop_column('invoices', 'issue_date')
    op.drop_column('invoices', 'cycle_month')
    op.drop_column('invoices', 'cycle_year')
    op.add_column('houses', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('houses', sa.Column('house_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_houses_house_code'), table_name='houses')
    op.create_index('ix_houses_house_no', 'houses', ['house_no'], unique=True)
    op.create_unique_constraint('houses_house_no_key', 'houses', ['house_no'])
    op.drop_column('houses', 'owner_name')
    op.drop_column('houses', 'house_status')
    op.drop_column('houses', 'house_code')
    op.create_table('invoice_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_recurring', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_items_invoice_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='invoice_items_pkey')
    )
    op.create_index('ix_invoice_items_id', 'invoice_items', ['id'], unique=False)
    op.drop_index(op.f('ix_invoice_payments_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_income_transactions_id'), table_name='income_transactions')
    op.drop_table('income_transactions')
    op.drop_index(op.f('ix_credit_notes_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    # ### end Alembic commands ###
