"""add_reference_bank_transaction_id_to_income_transactions

Revision ID: a43085327680
Revises: 6fc232d71afb
Create Date: 2026-01-17 14:15:28.967972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43085327680'
down_revision: Union[str, Sequence[str], None] = '6fc232d71afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_statement_batches_bank_account_id_fkey', 'bank_statement_batches', type_='foreignkey')
    op.drop_constraint('bank_statement_batches_uploaded_by_fkey', 'bank_statement_batches', type_='foreignkey')
    op.create_foreign_key(None, 'bank_statement_batches', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'bank_statement_batches', 'bank_accounts', ['bank_account_id'], ['id'])
    op.drop_index('ix_bank_transactions_batch_id', table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_effective_at', table_name='bank_transactions')
    op.drop_constraint('bank_transactions_bank_statement_batch_id_fkey', 'bank_transactions', type_='foreignkey')
    op.drop_constraint('bank_transactions_bank_account_id_fkey', 'bank_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'bank_transactions', 'bank_accounts', ['bank_account_id'], ['id'])
    op.create_foreign_key(None, 'bank_transactions', 'bank_statement_batches', ['bank_statement_batch_id'], ['id'])
    
    # Add reference_bank_transaction_id as NULLABLE first (for existing data)
    # New income_transactions will require this field via application logic
    op.add_column('income_transactions', sa.Column('reference_bank_transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'income_transactions', 'bank_transactions', ['reference_bank_transaction_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income_transactions', type_='foreignkey')
    op.drop_column('income_transactions', 'reference_bank_transaction_id')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.create_foreign_key('bank_transactions_bank_account_id_fkey', 'bank_transactions', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bank_transactions_bank_statement_batch_id_fkey', 'bank_transactions', 'bank_statement_batches', ['bank_statement_batch_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_bank_transactions_effective_at', 'bank_transactions', ['effective_at'], unique=False)
    op.create_index('ix_bank_transactions_batch_id', 'bank_transactions', ['bank_statement_batch_id'], unique=False)
    op.drop_constraint(None, 'bank_statement_batches', type_='foreignkey')
    op.drop_constraint(None, 'bank_statement_batches', type_='foreignkey')
    op.create_foreign_key('bank_statement_batches_uploaded_by_fkey', 'bank_statement_batches', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('bank_statement_batches_bank_account_id_fkey', 'bank_statement_batches', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
